#pragma once

#include <EASTL/vector.h>

#include <glm/vec2.hpp>
#include <glm/vec3.hpp>

#include <cstdint>

namespace GVM::ThreeSamples::ThreeCompat
{
    /** Evaluates one three-dimensional curve point for a normalized parameter. */
    using CurvePointFunction =
        glm::dvec3 (*)(double parameter, const void *context);

    /** Stores the indexed attributes generated by Three r185 TubeGeometry. */
    struct TubeMesh
    {
        eastl::vector<glm::vec3> positions;
        eastl::vector<glm::vec3> normals;
        eastl::vector<glm::vec2> textureCoordinates;
        eastl::vector<uint32_t> indices;
        eastl::vector<glm::dvec3> tangents;
        eastl::vector<glm::dvec3> frameNormals;
        eastl::vector<glm::dvec3> frameBinormals;
    };

    /** Describes one deterministic TubeGeometry build over an existing curve callback. */
    struct TubeMeshParameters
    {
        CurvePointFunction evaluatePoint = nullptr;
        const void *curveContext = nullptr;
        uint32_t tubularSegments = 64u;
        double radius = 1.0;
        uint32_t radialSegments = 8u;
        bool closed = false;
        uint32_t arcLengthDivisions = 200u;
    };

    /** Stores one arc-length-mapped curve sample and the curve's total sampled length. */
    struct TubeCurveSample
    {
        glm::dvec3 point{0.0};
        glm::dvec3 tangent{0.0};
        double totalLength = 0.0;
    };

    /** Evaluates the point, tangent, and total length used by Three r185 TubeGeometry at one normalized arc distance. */
    [[nodiscard]] TubeCurveSample sampleTubeCurve(
        const TubeMeshParameters &parameters,
        double normalizedDistance);

    /** Builds the exact indexed TubeGeometry layout and Frenet-frame sampling used by Three r185. */
    [[nodiscard]] TubeMesh buildTubeMesh(
        const TubeMeshParameters &parameters);
} // namespace GVM::ThreeSamples::ThreeCompat
