#ifndef GVM_THREE_WEBGL_POSTPROCESSING_GLITCH_HPP
#define GVM_THREE_WEBGL_POSTPROCESSING_GLITCH_HPP

#include "UGL.h"

using namespace UGL;

/*
 * This header is included by a dedicated sample shard after defining
 * THREE_BASIC_WebglPostprocessingGlitch.  The preprocessor only supplies the type prefix; all
 * rendering remains ordinary UGL DSL code and every generated shard owns its
 * own RenderSet, pass, and renderer symbols.
 */

/** Stores one normalized triangle-list vertex packed by the host adapter. */
struct ThreeBasicVertex
{
    float4 position [[Attribute0]];
    float4 normal [[Attribute1]];
};

/** Carries transformed clip coordinates and interpolated color to the fragment stage. */
struct ThreeBasicVertexOutput
{
    float4 position [[Position]];
    float4 color [[Attribute0]];
    float3 worldPosition [[Attribute1]];
    float3 worldNormal [[Attribute2]];
    uint entityID [[Attribute3]];
};

/** Stores one entity transform and material index in the Scene RenderSet. */
struct ThreeBasicObjectData
{
    float4 offsetAndScale;
    uint4 materialAndFlags;
    float4x4 viewProjection;
    float4 cameraPositionAndFog;
    float4 lightDirectionAndIntensity;
    float4 fogColorNearFar;
    float4 parentRotation;
};

/** Stores one per-instance transform and tint selected by the entity builtin. */
struct ThreeBasicInstanceData
{
    float4 positionAndScale;
    float4 rotation;
    float4 tint;
};

/** Stores one material color and the private semantic mode selected by C++. */
struct ThreeBasicMaterialData
{
    float4 baseColor;
};

/** Defines the single RenderSet used by this dedicated sample shard. */
struct WebglPostprocessingGlitchSceneRenderSet : public IRenderSet
{
    /** Declares consolidated geometry, object, instance, and material storage. */
    constructor(BufferComponent<ThreeBasicVertex> vertices [[RenderSetVertexBuffer]],
                BufferComponent<uint> indices [[RenderSetIndexBuffer]],
                BufferComponent<ThreeBasicObjectData> objects,
                BufferComponent<ThreeBasicInstanceData> instances,
                BufferComponent<ThreeBasicMaterialData> materials)
    {
    }
};

/** Defines the RGBA8 color and depth attachments used for deterministic capture. */
struct WebglPostprocessingGlitchFrameBuffer final : public IFrameBuffer
{
    ColorAttachment<TextureFormat::RGBA16Float> color;
    DepthStencilAttachment<TextureFormat::Depth32Float> depth;
};

/** Carries the fixed viewport, trigger time, and go-wild state to postprocessing. */
struct WebglPostprocessingGlitchEffectUniforms
{
    float4 viewportTimeWild;
    float4 glitchAmountAngleSeedBypass;
    float4 glitchSeedXYDistortionX;
    float4 glitchDistortionYAndColumn;
};

/** Binds the private displacement map generated by DSL Compute. */
struct WebglPostprocessingGlitchComputeResources final : public IBindGroup
{
    /** Declares the writable 64 by 64 height map and fixed effect controls. */
    constructor(
        RWTexture2D<TextureFormat::R32Float> displacement [[Binding0]],
        UniformBuffer<WebglPostprocessingGlitchEffectUniforms> uniforms [[Binding1]])
    {
    }
};

/** Binds one intermediate color texture and the generated displacement map. */
struct WebglPostprocessingGlitchScreenResources final : public IBindGroup
{
    /** Declares the source, displacement, samplers, and fixed effect controls. */
    constructor(
        Texture2D<float4> sourceColor [[Binding0]],
        Sampler sourceSampler [[Binding1]],
        Texture2D<float4> displacement [[Binding2]],
        Sampler displacementSampler [[Binding3]],
        UniformBuffer<WebglPostprocessingGlitchEffectUniforms> uniforms [[Binding4]])
    {
    }
};

/** Carries UV coordinates through the two fullscreen glitch passes. */
struct WebglPostprocessingGlitchScreenOutput
{
    float4 position [[Position]];
    float2 uv [[Attribute0]];
};

/** Defines an ordinary single-sample screen-pass color target. */
struct WebglPostprocessingGlitchScreenFrameBuffer final : public IFrameBuffer
{
    ColorAttachment<TextureFormat::RGBA16Float> color;
};

/** Defines the display-encoded single-sample capture attachment. */
struct WebglPostprocessingGlitchOutputFrameBuffer final : public IFrameBuffer
{
    ColorAttachment<TextureFormat::RGBA8Unorm> color;
};

/** Generates the deterministic displacement map entirely in DSL Compute. */
class [[LocalWorkGroupSize(8, 8, 1)]] WebglPostprocessingGlitchDisplacementPass final
    : public IComputeClass
{
public:
    /** Binds the writable effect texture and current fixed-step state. */
    constructor(BindGroup<WebglPostprocessingGlitchComputeResources> resources [[Slot0]])
    {
    }

private:
    /** Writes one bounded height-map texel from the pinned trigger stream. */
    void compute(uint3 threadID [[DispatchThreadID]])
    {
        if (threadID.x >= 64u || threadID.y >= 64u)
            return;
        const uint linearIndex = (63u - threadID.y) * 64u + threadID.x;
        uint randomState = 305419896u;
        const uint sampleCount = 1120u + linearIndex + 1u;
        for (uint sampleIndex = 0u; sampleIndex < sampleCount; ++sampleIndex)
        {
            randomState ^= randomState << 13u;
            randomState ^= randomState >> 17u;
            randomState ^= randomState << 5u;
        }
        const float randomValue = float(randomState >> 8u) / 16777216.0f;
        resources->displacement->write(threadID.xy, randomValue);
    }
};

/** Emits the shared fullscreen triangle used by both private effect passes. */
WebglPostprocessingGlitchScreenOutput webglPostprocessingGlitchFullscreenVertex(uint vertexID)
{
    const float2 uv = float2((vertexID << 1u) & 2u, vertexID & 2u);
    WebglPostprocessingGlitchScreenOutput outputValue;
    outputValue.position = float4(uv * 2.0f - 1.0f, 0.0f, 1.0f);
    outputValue.uv = uv;
    return outputValue;
}

/** Applies a bounded DigitalGlitch-style displacement to the Scene color. */
class WebglPostprocessingGlitchDigitalPass final : public IRenderClass
{
public:
    /** Binds the Scene color and Compute displacement textures. */
    constructor(BindGroup<WebglPostprocessingGlitchScreenResources> resources [[Slot0]])
    {
        setCullMode(CullMode::None);
        setDepthWriteEnabled(false);
    }

private:
    /** Emits one fullscreen triangle with normalized UV coordinates. */
    WebglPostprocessingGlitchScreenOutput vertex(uint vertexID [[VertexID]])
    {
        return webglPostprocessingGlitchFullscreenVertex(vertexID);
    }

    /** Samples the bounded displacement and emits a deterministic glitch image. */
    WebglPostprocessingGlitchScreenFrameBuffer fragment(WebglPostprocessingGlitchScreenOutput inputValue)
    {
        const float4 amountAngleSeedBypass = resources->uniforms->glitchAmountAngleSeedBypass;
        const float4 seedXYDistortionX = resources->uniforms->glitchSeedXYDistortionX;
        const float4 distortionYAndColumn = resources->uniforms->glitchDistortionYAndColumn;
        const float bypass = amountAngleSeedBypass.w;
        const float2 referenceUv = float2(
            inputValue.uv.x, 1.0f - inputValue.uv.y);
        float2 sampleUv = referenceUv;
        if (bypass < 0.5f)
        {
            const float amount = amountAngleSeedBypass.x;
            const float angle = amountAngleSeedBypass.y;
            const float seed = amountAngleSeedBypass.z;
            const float seedX = seedXYDistortionX.x;
            const float seedY = seedXYDistortionX.y;
            const float distortionX = seedXYDistortionX.z;
            const float distortionY = seedXYDistortionX.w;
            const float columnWidth = distortionYAndColumn.y;
            const float2 displacementUv = frac(referenceUv * seed * seed);
            const float2 displacementStorageUv = float2(
                displacementUv.x, 1.0f - displacementUv.y);
            const uint2 displacementCoordinate = uint2(min(
                floor(displacementStorageUv * 64.0f), float2(63.0f)));
            const float displacementSample = resources->displacement->read(
                displacementCoordinate, 0u).x;
            if (referenceUv.y < distortionX + columnWidth &&
                referenceUv.y > distortionX - columnWidth * seed)
            {
                sampleUv.y = seedX > 0.0f
                    ? 1.0f - (referenceUv.y + distortionY)
                    : distortionY;
            }
            if (referenceUv.x < distortionY + columnWidth &&
                referenceUv.x > distortionY - columnWidth * seed)
            {
                sampleUv.x = seedY > 0.0f
                    ? distortionX
                    : 1.0f - (inputValue.uv.x + distortionX);
            }
            sampleUv += displacementSample * float2(seedX, seedY) * (seed / 5.0f);
            const float2 offset = amount * float2(cos(angle), sin(angle));
            const float2 redUv = float2(
                sampleUv.x + offset.x, 1.0f - (sampleUv.y + offset.y));
            const float2 greenUv = float2(
                sampleUv.x, 1.0f - sampleUv.y);
            const float2 blueUv = float2(
                sampleUv.x - offset.x, 1.0f - (sampleUv.y - offset.y));
            const float4 red = resources->sourceColor->sample(
                resources->sourceSampler, redUv);
            const float4 green = resources->sourceColor->sample(
                resources->sourceSampler, greenUv);
            const float4 blue = resources->sourceColor->sample(
                resources->sourceSampler, blueUv);
            const float fragmentX = floor(inputValue.position.x / 0.5f);
            const float fragmentY = floor(
                (resources->uniforms->viewportTimeWild.y - inputValue.position.y) / 0.5f);
            const float2 noiseCoordinate = float2(
                fragmentX * seed,
                fragmentY * seed * 50.0f);
            const float noiseSeed = sin(dot(
                noiseCoordinate, float2(12.9898f, 78.233f))) * 43758.5453f;
            const float snow = 200.0f * amount * (noiseSeed - floor(noiseSeed)) * 0.2f;
            const float3 rgb = float3(red.r, green.g, blue.b) + float3(snow);
            WebglPostprocessingGlitchScreenFrameBuffer frameBuffer;
            frameBuffer.color = half4(half3(rgb), half(green.a));
            return frameBuffer;
        }
        const float4 source = resources->sourceColor->sample(
            resources->sourceSampler, inputValue.uv);
        WebglPostprocessingGlitchScreenFrameBuffer frameBuffer;
        frameBuffer.color = half4(source);
        return frameBuffer;
    }
};

/** Converts the intermediate glitch image into the final capture attachment. */
float webglPostprocessingGlitchLinearToSrgb(float value)
{
    return value <= 0.0031308f
        ? value * 12.92f
        : pow(value, 0.4166666666666667f) * 1.055f - 0.055f;
}

class WebglPostprocessingGlitchOutputPass final : public IRenderClass
{
public:
    /** Binds the intermediate screen color and disables depth state. */
    constructor(BindGroup<WebglPostprocessingGlitchScreenResources> resources [[Slot0]])
    {
        setCullMode(CullMode::None);
        setDepthWriteEnabled(false);
    }

private:
    /** Emits one fullscreen triangle. */
    WebglPostprocessingGlitchScreenOutput vertex(uint vertexID [[VertexID]])
    {
        return webglPostprocessingGlitchFullscreenVertex(vertexID);
    }

    /** Preserves the intermediate RGBA values for the host capture. */
    WebglPostprocessingGlitchOutputFrameBuffer fragment(WebglPostprocessingGlitchScreenOutput inputValue)
    {
        const float4 source = resources->sourceColor->sample(resources->sourceSampler, inputValue.uv);
        WebglPostprocessingGlitchOutputFrameBuffer frameBuffer;
        frameBuffer.color = half4(
            half3(
                saturate(webglPostprocessingGlitchLinearToSrgb(source.x)),
                saturate(webglPostprocessingGlitchLinearToSrgb(source.y)),
                saturate(webglPostprocessingGlitchLinearToSrgb(source.z))),
            half(source.a));
        return frameBuffer;
    }
};

/** Applies Three's intrinsic XYZ Euler rotation order to one local direction. */
float3 webglPostprocessingGlitchRotateXYZ(float3 value, float3 rotation)
{
    const float sx = sin(rotation.x);
    const float cx = cos(rotation.x);
    const float sy = sin(rotation.y);
    const float cy = cos(rotation.y);
    const float sz = sin(rotation.z);
    const float cz = cos(rotation.z);
    const float3 zRotated = float3(
        value.x * cz - value.y * sz,
        value.x * sz + value.y * cz,
        value.z);
    const float3 yRotated = float3(
        zRotated.x * cy + zRotated.z * sy,
        zRotated.y,
        -zRotated.x * sy + zRotated.z * cy);
    return float3(
        yRotated.x,
        yRotated.y * cx - yRotated.z * sx,
        yRotated.y * sx + yRotated.z * cx);
}

/**
 * Draws all entities through the Scene RenderSet indexed-indirect path.
 * The shader contains the common Three-compatible vertex-color, lighting,
 * clipping, and deterministic animation operations used by this wave.
 */
class WebglPostprocessingGlitchMainPass final : public IRenderClass
{
public:
    /** Binds the unique Scene RenderSet and enables depth-tested opaque drawing. */
    constructor(RenderSet<WebglPostprocessingGlitchSceneRenderSet> sceneSet [[Slot0]])
    {
        setCullMode(CullMode::Front);
        setDepthWriteEnabled(true);
        setDepthCompareFunction(CompareFunction::LessEqual);
    }

private:
    /** Resolves per-entity and per-instance data through the RenderEntity builtins. */
    ThreeBasicVertexOutput vertex(
        ThreeBasicVertex inputValue [[VertexInput0]],
        uint renderEntityID [[RenderEntityID]],
        uint renderEntityInstanceID [[RenderEntityInstanceID]])
    {
        const ThreeBasicObjectData objectData = sceneSet->objects->get(renderEntityID, 0u);
        const ThreeBasicInstanceData instanceData =
            sceneSet->instances->get(renderEntityID, renderEntityInstanceID);
        const float3 localDirection = inputValue.position.xyz;
        const float3 parentRotation = objectData.parentRotation.xyz;
        const float3 instanceRotation = instanceData.rotation.xyz;
        const float3 instancePosition = instanceData.positionAndScale.xyz;
        const float3 rotatedDirection = webglPostprocessingGlitchRotateXYZ(
            localDirection, instanceRotation);
        const float3 parentPosition = webglPostprocessingGlitchRotateXYZ(
            instancePosition, parentRotation);
        const float3 worldPosition = webglPostprocessingGlitchRotateXYZ(
            rotatedDirection * instanceData.positionAndScale.w,
            parentRotation) + parentPosition;
        const float3 worldNormal = normalize(webglPostprocessingGlitchRotateXYZ(
            webglPostprocessingGlitchRotateXYZ(
                normalize(float3(inputValue.normal.xyz)), instanceRotation),
            parentRotation));
        ThreeBasicVertexOutput outputValue;
        float4 clipPosition = mul(objectData.viewProjection, float4(worldPosition, 1.0f));
        // Three's WebGL clip convention is converted to the DSL/RHI viewport
        // convention exactly once at the Scene boundary.
        clipPosition.y = -clipPosition.y;
        clipPosition.z = (clipPosition.z + clipPosition.w) * 0.5f;
        outputValue.position = clipPosition;
        outputValue.color = instanceData.tint;
        outputValue.worldPosition = worldPosition;
        outputValue.worldNormal = worldNormal;
        outputValue.entityID = renderEntityID;
        return outputValue;
    }

    /** Applies the material component and a stable linear-to-sRGB transfer. */
    WebglPostprocessingGlitchFrameBuffer fragment(
        ThreeBasicVertexOutput inputValue)
    {
        const ThreeBasicObjectData objectData = sceneSet->objects->get(inputValue.entityID, 0u);
        const ThreeBasicMaterialData materialData = sceneSet->materials->get(
            inputValue.entityID,
            objectData.materialAndFlags.x);
        const float3 normal = normalize(inputValue.worldNormal);
        const float3 cameraPosition = objectData.cameraPositionAndFog.xyz;
        const float3 cameraToFragment = cameraPosition - inputValue.worldPosition;
        const float3 viewDirection = normalize(cameraToFragment);
        const float3 lightDirectionValue = objectData.lightDirectionAndIntensity.xyz;
        const float3 lightDirection = normalize(lightDirectionValue);
        const float diffuse = saturate(dot(normal, lightDirection));
        const float3 halfDirection = normalize(lightDirection + viewDirection);
        const float normalHalf = saturate(dot(normal, halfDirection));
        const float viewHalf = saturate(dot(viewDirection, halfDirection));
        const float fresnelFactor = exp2(
            (-5.55473f * viewHalf - 6.98316f) * viewHalf);
        const float3 specularFresnel = float3(0.0056053917f) *
            (1.0f - fresnelFactor) + float3(fresnelFactor);
        const float inversePi = 0.3183098861837907f;
        const float distribution = inversePi * 16.0f * pow(normalHalf, 30.0f);
        const float3 diffuseColor = inputValue.color.xyz * materialData.baseColor.xyz;
        const float3 directIrradiance = float3(
            diffuse * objectData.lightDirectionAndIntensity.w);
        const float3 directDiffuse = directIrradiance * diffuseColor * inversePi;
        const float3 indirectDiffuse = float3(0.60382736f) * diffuseColor * inversePi;
        const float3 directSpecular = directIrradiance * specularFresnel *
            (0.25f * distribution);
        const float3 litColor = directDiffuse + indirectDiffuse + directSpecular;
        const float viewDepth = objectData.cameraPositionAndFog.z - inputValue.worldPosition.z;
        const float fogLinear = saturate(
            (viewDepth - objectData.cameraPositionAndFog.w) /
            max(objectData.fogColorNearFar.w - objectData.cameraPositionAndFog.w, 0.0001f));
        const float fogFactor = fogLinear * fogLinear *
            (3.0f - 2.0f * fogLinear);
        const float3 fogColor = objectData.fogColorNearFar.xyz;
        const float3 linearColor = saturate(lerp(litColor, fogColor, fogFactor));
        WebglPostprocessingGlitchFrameBuffer frameBuffer;
        // The EffectComposer render target is linear; OutputPass performs the
        // sole transfer to the display-encoded capture at the end of the chain.
        frameBuffer.color = half4(half3(linearColor), half(1.0f));
        return frameBuffer;
    }
};

/** Owns this shard's unique RenderSet, Scene pass, and single-sample targets. */
class WebglPostprocessingGlitchRenderer final : public AbstractRenderer
{
    Device device;
    Swapchain swapchain;
    Queue graphicsQueue;
    [[Export]] RenderSet<WebglPostprocessingGlitchSceneRenderSet> sceneSet;
    RenderClass<WebglPostprocessingGlitchMainPass> scenePass;
    ComputeClass<WebglPostprocessingGlitchDisplacementPass> displacementPass;
    RenderClass<WebglPostprocessingGlitchDigitalPass> digitalPass;
    RenderClass<WebglPostprocessingGlitchOutputPass> outputPass;
    Buffer<WebglPostprocessingGlitchEffectUniforms,
           BufferUsage<Uniform, CopyDst>> effectUniforms;
    Texture<TextureFormat::R32Float,
            TextureUsage<StorageBinding, TextureBinding>,
            TextureDimension::e2D>
        displacementTexture;
    Texture<TextureFormat::RGBA16Float,
            TextureUsage<RenderAttachment, TextureBinding>,
            TextureDimension::e2D>
        sceneColor;
    Texture<TextureFormat::RGBA16Float,
            TextureUsage<RenderAttachment, TextureBinding>,
            TextureDimension::e2D>
        glitchColor;
    Sampler effectSampler;
    Sampler displacementSampler;
    BindGroup<WebglPostprocessingGlitchComputeResources> computeResources;
    BindGroup<WebglPostprocessingGlitchScreenResources> digitalResources;
    BindGroup<WebglPostprocessingGlitchScreenResources> outputResources;
    Texture<TextureFormat::RGBA8Unorm,
            TextureUsage<RenderAttachment, TextureBinding, CopySrc>,
            TextureDimension::e2D>
        outputColor;
    Texture<TextureFormat::Depth32Float,
            TextureUsage<RenderAttachment>,
            TextureDimension::e2D>
        outputDepth;
    uint readbackWidth = 800u;
    uint readbackHeight = 500u;
    float effectTime = 0.0f;
    bool effectWild = false;
    float effectAmount = 0.0f;
    float effectAngle = 0.0f;
    float effectSeed = 0.0f;
    float effectSeedX = 0.0f;
    float effectSeedY = 0.0f;
    float effectDistortionX = 0.0f;
    float effectDistortionY = 0.0f;
    float effectColumnWidth = 0.05f;
    float effectBypass = 1.0f;
    bool displacementReady = false;

public:
    /** Creates this shard's RenderSet and its generated Scene RenderClass. */
    void init(Device inDevice, Swapchain inSwapchain) override
    {
        device = inDevice;
        swapchain = inSwapchain;
        graphicsQueue = device->graphicsQueue(0);
        sceneSet = device->createRenderSet<WebglPostprocessingGlitchSceneRenderSet>();
        scenePass = device->createRenderClass<WebglPostprocessingGlitchMainPass>(sceneSet);
    }

    /** Recreates the explicit single-sample capture attachments. */
    void configureOutput(uint width, uint height)
    {
        readbackWidth = width;
        readbackHeight = height;
        outputColor = device->createTexture("ThreeBasicRenderSetColor", width, height, 1u);
        outputDepth = device->createTexture("ThreeBasicRenderSetDepth", width, height, 1u);
        sceneColor = device->createTexture(
            "WebglPostprocessingGlitchSceneColor", width, height, 1u);
        glitchColor = device->createTexture(
            "WebglPostprocessingGlitchIntermediateColor", width, height, 1u);
        displacementTexture = device->createTexture(
            "WebglPostprocessingGlitchDisplacement", 64u, 64u, 1u);
        effectUniforms = device->createBuffer(
            "WebglPostprocessingGlitchEffectUniforms", 1u);
        effectSampler = device->createSampler({
            .label = "WebglPostprocessingGlitchLinearSampler",
            .addressModeU = AddressMode::ClampToEdge,
            .addressModeV = AddressMode::ClampToEdge,
            .addressModeW = AddressMode::ClampToEdge,
            .magFilter = FilterMode::Linear,
            .minFilter = FilterMode::Linear,
            .mipmapFilter = MipmapFilterMode::Nearest,
        });
        displacementSampler = device->createSampler({
            .label = "WebglPostprocessingGlitchDisplacementSampler",
            .addressModeU = AddressMode::ClampToEdge,
            .addressModeV = AddressMode::ClampToEdge,
            .addressModeW = AddressMode::ClampToEdge,
            .magFilter = FilterMode::Nearest,
            .minFilter = FilterMode::Nearest,
            .mipmapFilter = MipmapFilterMode::Nearest,
        });
        computeResources = device->createBindGroup<
            WebglPostprocessingGlitchComputeResources>(
                displacementTexture->createView(), effectUniforms);
        digitalResources = device->createBindGroup<
            WebglPostprocessingGlitchScreenResources>(
                sceneColor->createView(), effectSampler,
                displacementTexture->createView(), displacementSampler,
                effectUniforms);
        outputResources = device->createBindGroup<
            WebglPostprocessingGlitchScreenResources>(
                glitchColor->createView(), effectSampler,
                displacementTexture->createView(), displacementSampler,
                effectUniforms);
        displacementPass = device->createComputeClass<
            WebglPostprocessingGlitchDisplacementPass>(computeResources);
        digitalPass = device->createRenderClass<
            WebglPostprocessingGlitchDigitalPass>(digitalResources);
        outputPass = device->createRenderClass<
            WebglPostprocessingGlitchOutputPass>(outputResources);
    }

    /** Stores the host-replayed GlitchPass uniforms for the capture frame. */
    void configureEffect(float time, float amount, float angle, float seed,
                         float seedX, float seedY, float distortionX,
                         float distortionY, float columnWidth, float bypass,
                         bool wild)
    {
        effectTime = time;
        effectWild = wild;
        effectAmount = amount;
        effectAngle = angle;
        effectSeed = seed;
        effectSeedX = seedX;
        effectSeedY = seedY;
        effectDistortionX = distortionX;
        effectDistortionY = distortionY;
        effectColumnWidth = columnWidth;
        effectBypass = bypass;
    }

    /** Applies pending RenderSet commands and submits one indexed-indirect Scene pass. */
    void render() override
    {
        sceneSet->update();
        WebglPostprocessingGlitchEffectUniforms uniforms;
        uniforms.viewportTimeWild = float4(
            float(readbackWidth),
            float(readbackHeight),
            effectTime,
            effectWild ? 1.0f : 0.0f);
        uniforms.glitchAmountAngleSeedBypass = float4(
            effectAmount, effectAngle, effectSeed, effectBypass);
        uniforms.glitchSeedXYDistortionX = float4(
            effectSeedX, effectSeedY, effectDistortionX, effectDistortionY);
        uniforms.glitchDistortionYAndColumn = float4(
            effectDistortionY, effectColumnWidth, effectWild ? 1.0f : 0.05f, 0.0f);
        const auto nextTexture = swapchain->queryNextTexture();
        WebglPostprocessingGlitchFrameBuffer frameBuffer;
        frameBuffer.color = sceneColor->createView();
        frameBuffer.color.loadOp = LoadOp::Clear;
        frameBuffer.color.storeOp = StoreOp::Store;
        // Three.Scene defaults to a black clear color; the glitch example does
        // not assign a scene background before RenderPass captures it.
        frameBuffer.color.clearValue = {0.0, 0.0, 0.0, 1.0};
        frameBuffer.depth = outputDepth->createView();
        frameBuffer.depth.depthLoadOp = LoadOp::Clear;
        frameBuffer.depth.depthStoreOp = StoreOp::Store;
        frameBuffer.depth.depthClearValue = 1.0f;
        WebglPostprocessingGlitchScreenFrameBuffer digitalFrameBuffer;
        digitalFrameBuffer.color = glitchColor->createView();
        digitalFrameBuffer.color.loadOp = LoadOp::Clear;
        digitalFrameBuffer.color.storeOp = StoreOp::Store;
        digitalFrameBuffer.color.clearValue = {0.0, 0.0, 0.0, 1.0};
        WebglPostprocessingGlitchOutputFrameBuffer outputFrameBuffer;
        outputFrameBuffer.color = outputColor->createView();
        outputFrameBuffer.color.loadOp = LoadOp::Clear;
        outputFrameBuffer.color.storeOp = StoreOp::Store;
        outputFrameBuffer.color.clearValue = {0.0, 0.0, 0.0, 1.0};
        graphicsQueue->writeBuffer(
            BufferRange(effectUniforms), &uniforms, sizeof(uniforms))->submit();
        if (!displacementReady)
        {
            graphicsQueue->computePass(
                "WebglPostprocessingGlitchDisplacement",
                displacementPass(64u, 64u, 1u))->submit();
            displacementReady = true;
        }
        graphicsQueue
            ->renderPass("WebglPostprocessingGlitchScene", frameBuffer, scenePass())
            ->renderPass("WebglPostprocessingGlitchDigital", digitalFrameBuffer, digitalPass(3u, 1u, 0u, 0u))
            ->renderPass("WebglPostprocessingGlitchOutput", outputFrameBuffer, outputPass(3u, 1u, 0u, 0u))
            ->renderToSwapchain(nextTexture, outputColor, RenderToSwapchainDescriptor{})
            ->submit();
        swapchain->present();
    }

    /** Returns the DSL-owned RGBA8 target used for deterministic readback. */
    Texture<TextureFormat::RGBA8Unorm,
            TextureUsage<RenderAttachment, TextureBinding, CopySrc>,
            TextureDimension::e2D>
    getReadbackTextureHandle() const
    {
        return outputColor;
    }

    /** Returns the explicit capture width. */
    uint getReadbackWidth() const
    {
        return readbackWidth;
    }

    /** Returns the explicit capture height. */
    uint getReadbackHeight() const
    {
        return readbackHeight;
    }

    /** Releases the single-sample attachments and RenderSet after capture. */
    void destroy() override
    {
        sceneSet->destroy();
        device->freeBuffer(effectUniforms);
        device->freeTexture(displacementTexture);
        device->freeTexture(sceneColor);
        device->freeTexture(glitchColor);
        device->freeTexture(outputColor);
        device->freeTexture(outputDepth);
    }
};

#undef WebglPostprocessingGlitchRenderer
#undef WebglPostprocessingGlitchFrameBuffer
#undef WebglPostprocessingGlitchMainPass
#undef WebglPostprocessingGlitchSceneRenderSet
#undef THREE_BASIC_JOIN

#endif
