#include "BuffergeometryInterleavedRuntimeAdapter.hpp"

#include "Fixtures/Phase1TextureCases/GifImageDecoder.hpp"
#include "ThreeCompat/DeterministicRandom.hpp"
#include "UGLBin/exports.hpp"

#include <GVMCore/Public/GAbstractRenderSetCommandEncoder.hpp>
#include <GVMCore/Public/GRenderSetCommand.hpp>

#include <glm/gtc/quaternion.hpp>
#include <glm/gtx/quaternion.hpp>

#include <cmath>
#include <filesystem>
#include <fstream>
#include <limits>
#include <stdexcept>

namespace GVM::ThreeSamples
{
    namespace
    {
        constexpr uint32_t InstanceCount = 5000u;
        constexpr uint32_t PreInstanceRandomDrawCount = 108u;
        constexpr uint32_t RandomDrawsPerInstance = 7u;
        constexpr uint32_t ExpectedFinalRandomState = 255858576u;
        constexpr uint32_t CrateExtent = 256u;
        constexpr uint32_t CrateMipCount = 9u;
        constexpr GVM::Core::RenderSetHandle SceneRenderSetHandle =
            ExportedRenderSet::sceneSet;

        static_assert(sizeof(BuffergeometryClosureHostUint4) == 16u);
        static_assert(sizeof(BuffergeometryInterleavedHostObjectData) == 80u);
        static_assert(sizeof(BuffergeometryInterleavedHostInstanceData) == 64u);
        static_assert(sizeof(BuffergeometryInterleavedHostMaterialData) == 16u);
        static_assert(
            PreInstanceRandomDrawCount +
                InstanceCount * RandomDrawsPerInstance ==
            35108u);

        /** Creates parent directories for one explicitly requested artifact. */
        void prepareInterleavedOutputPath(
            const std::filesystem::path &outputPath)
        {
            if (!outputPath.parent_path().empty())
            {
                std::filesystem::create_directories(
                    outputPath.parent_path());
            }
        }

        /** Returns the shared upper-24-bit JavaScript random unit double. */
        double nextInterleavedRandomUnit(
            ThreeCompat::DeterministicRandom &random)
        {
            return double(random.nextUint32() >> 8u) / 16777216.0;
        }

        /** Validates the two immutable manifest scenarios and fixed host contract. */
        void validateInterleavedScenario(
            const ThreeSampleHostOptions &options)
        {
            const bool initial =
                options.scenarioId == "initial" &&
                options.targetFrame == 0u;
            const bool animated =
                options.scenarioId == "animated" &&
                options.targetFrame == 60u;
            if (options.caseId !=
                    "webgl_buffergeometry_instancing_interleaved" ||
                (!initial && !animated) ||
                options.width != 800u ||
                options.height != 500u ||
                options.randomSeed != DefaultThreeRandomSeed ||
                !options.inputReplayPath.empty() ||
                options.assetRoot.empty())
            {
                throw std::invalid_argument(
                    "Interleaved instancing requires its exact case, scenario, extent, seed, asset root, and no replay.");
            }
        }

        /** Reproduces the virtual 60 Hz performance clock at one target frame. */
        double interleavedVirtualTimeMilliseconds(uint32_t frameIndex)
        {
            double milliseconds = 0.0;
            for (uint32_t index = 0u; index < frameIndex; ++index)
            {
                milliseconds += 1000.0 / 60.0;
            }
            return milliseconds;
        }

        /** Returns one normalized quaternion generated by the r185 random stream. */
        glm::quat makeInterleavedRandomQuaternion(
            ThreeCompat::DeterministicRandom &random)
        {
            const double x = nextInterleavedRandomUnit(random) * 2.0 - 1.0;
            const double y = nextInterleavedRandomUnit(random) * 2.0 - 1.0;
            const double z = nextInterleavedRandomUnit(random) * 2.0 - 1.0;
            const double w = nextInterleavedRandomUnit(random) * 2.0 - 1.0;
            const double length =
                std::sqrt(x * x + y * y + z * z + w * w);
            if (!(length > 0.0))
            {
                throw std::runtime_error(
                    "Interleaved random stream produced a zero quaternion.");
            }
            return glm::quat(
                float(w / length),
                float(x / length),
                float(y / length),
                float(z / length));
        }

        /** Builds the exact Float32 instance matrices at one deterministic frame. */
        uint32_t buildInterleavedInstances(
            uint32_t frameIndex,
            eastl::vector<BuffergeometryInterleavedHostInstanceData> &instances)
        {
            ThreeCompat::DeterministicRandom random(DefaultThreeRandomSeed);
            for (uint32_t draw = 0u;
                 draw < PreInstanceRandomDrawCount;
                 ++draw)
            {
                (void)random.nextUint32();
            }

            const double targetTime =
                interleavedVirtualTimeMilliseconds(frameIndex);
            const glm::dvec3 moveAxis =
                glm::normalize(glm::dvec3(0.5, 0.5, 0.5));
            eastl::vector<glm::mat4> matrices;
            matrices.reserve(InstanceCount);
            for (uint32_t instanceIndex = 0u;
                 instanceIndex < InstanceCount;
                 ++instanceIndex)
            {
                const glm::dvec3 rawOffset(
                    nextInterleavedRandomUnit(random) * 100.0 - 50.0,
                    nextInterleavedRandomUnit(random) * 100.0 - 50.0,
                    nextInterleavedRandomUnit(random) * 100.0 - 50.0);
                const glm::dvec3 offset =
                    rawOffset + glm::normalize(rawOffset) * 5.0;
                const glm::quat orientation =
                    makeInterleavedRandomQuaternion(random);
                glm::mat4 matrix = glm::toMat4(orientation);
                matrix[3u] = glm::vec4(
                    float(offset.x),
                    float(offset.y),
                    float(offset.z),
                    1.0f);
                matrices.push_back(matrix);
            }
            if (random.getState() != ExpectedFinalRandomState)
            {
                throw std::runtime_error(
                    "Interleaved instance random stream diverged from r185.");
            }

            if (frameIndex != 0u)
            {
                double lastTime = 0.0;
                for (uint32_t renderedFrame = 0u;
                     renderedFrame <= frameIndex;
                     ++renderedFrame)
                {
                    const double currentTime =
                        renderedFrame == frameIndex
                            ? targetTime
                            : interleavedVirtualTimeMilliseconds(
                                  renderedFrame);
                    const double delta =
                        (currentTime - lastTime) / 5000.0;
                    glm::dquat incremental(
                        1.0,
                        moveAxis.x * delta,
                        moveAxis.y * delta,
                        moveAxis.z * delta);
                    incremental = glm::normalize(incremental);
                    const glm::mat4 incrementalMatrix =
                        glm::mat4_cast(glm::quat(incremental));
                    for (glm::mat4 &matrix : matrices)
                    {
                        matrix = matrix * incrementalMatrix;
                    }
                    lastTime = currentTime;
                }
            }

            instances.clear();
            instances.reserve(InstanceCount);
            for (const glm::mat4 &matrix : matrices)
            {
                instances.push_back({
                    {matrix[0u].x, matrix[0u].y, matrix[0u].z, matrix[0u].w},
                    {matrix[1u].x, matrix[1u].y, matrix[1u].z, matrix[1u].w},
                    {matrix[2u].x, matrix[2u].y, matrix[2u].z, matrix[2u].w},
                    {matrix[3u].x, matrix[3u].y, matrix[3u].z, matrix[3u].w},
                });
            }
            return random.getState();
        }

        /** Builds the root y rotation and r185 perspective at the target frame. */
        glm::mat4 makeInterleavedRootProjection(
            uint32_t width,
            uint32_t height,
            uint32_t frameIndex)
        {
            const double rotationY =
                interleavedVirtualTimeMilliseconds(frameIndex) * 0.00005;
            glm::mat4 root(1.0f);
            root[0u][0u] = float(std::cos(rotationY));
            root[0u][2u] = float(-std::sin(rotationY));
            root[2u][0u] = float(std::sin(rotationY));
            root[2u][2u] = float(std::cos(rotationY));
            constexpr double Pi = 3.14159265358979323846;
            constexpr double NearDistance = 1.0;
            constexpr double FarDistance = 1000.0;
            const double top =
                NearDistance * std::tan(50.0 * Pi / 360.0);
            const double projectionHeight = top * 2.0;
            const double projectionWidth =
                (double(width) / double(height)) * projectionHeight;
            const double depth = FarDistance - NearDistance;
            glm::mat4 projection(0.0f);
            projection[0u][0u] =
                float(2.0 * NearDistance / projectionWidth);
            projection[1u][1u] =
                float(-2.0 * NearDistance / projectionHeight);
            projection[2u][2u] =
                float(-FarDistance / depth);
            projection[2u][3u] = -1.0f;
            projection[3u][2u] =
                float(-FarDistance * NearDistance / depth);
            return projection * root;
        }

        /** Builds the exact 24-record interleaved cube and authored index order. */
        void buildInterleavedBoxGeometry(
            eastl::vector<TexturedBoxHostVertex> &vertices,
            eastl::vector<uint32_t> &indices)
        {
            const float source[24u][5u] = {
                {-1, 1, 1, 0, 0}, {1, 1, 1, 1, 0},
                {-1, -1, 1, 0, 1}, {1, -1, 1, 1, 1},
                {1, 1, -1, 1, 0}, {-1, 1, -1, 0, 0},
                {1, -1, -1, 1, 1}, {-1, -1, -1, 0, 1},
                {-1, 1, -1, 1, 1}, {-1, 1, 1, 1, 0},
                {-1, -1, -1, 0, 1}, {-1, -1, 1, 0, 0},
                {1, 1, 1, 1, 0}, {1, 1, -1, 1, 1},
                {1, -1, 1, 0, 0}, {1, -1, -1, 0, 1},
                {-1, 1, 1, 0, 0}, {1, 1, 1, 1, 0},
                {-1, 1, -1, 0, 1}, {1, 1, -1, 1, 1},
                {1, -1, 1, 1, 0}, {-1, -1, 1, 0, 0},
                {1, -1, -1, 1, 1}, {-1, -1, -1, 0, 1},
            };
            vertices.clear();
            vertices.reserve(24u);
            for (const auto &record : source)
            {
                vertices.push_back({
                    .position = {
                        record[0u],
                        record[1u],
                        record[2u],
                        1.0f},
                    .texCoord = {
                        record[3u],
                        record[4u],
                        0.0f,
                        0.0f},
                });
            }
            const uint32_t sourceIndices[36u] = {
                0, 2, 1, 2, 3, 1,
                4, 6, 5, 6, 7, 5,
                8, 10, 9, 10, 11, 9,
                12, 14, 13, 14, 15, 13,
                16, 17, 18, 18, 17, 19,
                20, 21, 22, 22, 21, 23,
            };
            indices.assign(sourceIndices, sourceIndices + 36u);
        }

        /** Appends one typed host payload to a RenderSet allocation. */
        void appendInterleavedBufferPayload(
            GVM::Core::RenderSetAllocInfo &allocation,
            GVM::Core::RenderComponentHandle component,
            const char *name,
            const void *value,
            uint64_t byteCount,
            uint32_t instanceCount)
        {
            allocation.bufferInfos.push_back({
                .bufferComponentHandle = component,
                .bufferName = name,
                .value = value,
                .dataStorageSize = byteCount,
                .instanceCount = instanceCount,
            });
        }

        /** Appends the locked crate mip chain to the entity TextureComponent. */
        void appendInterleavedCrateTexture(
            GVM::Core::RenderSetAllocInfo &allocation,
            const eastl::vector<uint8_t> &textureBytes,
            const eastl::vector<uint64_t> &mipOffsets)
        {
            GVM::Core::RenderSetTextureComponentAllocInfo textureComponent;
            textureComponent.textureComponentHandle =
                WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                    textures;
            textureComponent.textures.push_back({
                .textureName =
                    "WebglBuffergeometryInstancingInterleavedCrateSrgb",
                .format = GVM::RHI::TextureFormat::RGBA8UnormSrgb,
                .width = CrateExtent,
                .height = CrateExtent,
                .data = textureBytes.data(),
                .dataStorageBytes = textureBytes.size(),
                .mipmapOffsetBytes = mipOffsets,
            });
            allocation.textureInfos.push_back(eastl::move(textureComponent));
        }

    } // namespace

    void BuffergeometryInterleavedRuntimeAdapter::initializeResources(
        GVM::Core::AbstractRendererImpl &renderer,
        GVM::Core::DeviceProxy inDevice,
        const ThreeSampleHostOptions &options)
    {
        validateInterleavedScenario(options);
        device = inDevice;
        buildInterleavedBoxGeometry(vertices, indices);
        finalRandomState =
            buildInterleavedInstances(options.targetFrame, instances);

        const std::filesystem::path cratePath =
            std::filesystem::path(options.assetRoot.c_str()) /
            "textures" /
            "crate.gif";
        const RgbaImageData crate = decodeGifRgba8(cratePath);
        if (crate.width != CrateExtent || crate.height != CrateExtent)
        {
            throw std::runtime_error(
                "Interleaved crate asset is not the locked 256x256 image.");
        }
        const eastl::vector<RgbaImageData> mipChain =
            buildSrgbMipChain(crate);
        if (mipChain.size() != CrateMipCount)
        {
            throw std::runtime_error(
                "Interleaved crate asset did not produce nine mip levels.");
        }
        for (const RgbaImageData &mip : mipChain)
        {
            crateMipOffsets.push_back(crateTextureBytes.size());
            crateTextureBytes.insert(
                crateTextureBytes.end(),
                mip.pixels.begin(),
                mip.pixels.end());
        }

        const BuffergeometryInterleavedHostObjectData objectData = {
            .rootModelViewProjection = makeInterleavedRootProjection(
                options.width,
                options.height,
                options.targetFrame),
            .materialAndFlags = {0u, 0u, 0u, 0u},
        };
        const BuffergeometryInterleavedHostMaterialData materialData = {
            .baseColor = {1.0f, 1.0f, 1.0f, 1.0f},
        };

        const auto encoder =
            renderer.createRenderSetCommandEncoder(SceneRenderSetHandle);
        if (!encoder)
        {
            throw std::runtime_error(
                "Interleaved example could not create its Scene RenderSet encoder.");
        }
        GVM::Core::RenderSetAllocInfo allocation;
        allocation.verticesCount =
            static_cast<uint32_t>(vertices.size());
        allocation.indicesCount =
            static_cast<uint32_t>(indices.size());
        allocation.instanceCount = InstanceCount;
        appendInterleavedBufferPayload(
            allocation,
            WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                vertices,
            "WebglBuffergeometryInstancingInterleavedVertices",
            vertices.data(),
            vertices.size() * sizeof(TexturedBoxHostVertex),
            1u);
        appendInterleavedBufferPayload(
            allocation,
            WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                indices,
            "WebglBuffergeometryInstancingInterleavedIndices",
            indices.data(),
            indices.size() * sizeof(uint32_t),
            1u);
        appendInterleavedBufferPayload(
            allocation,
            WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                objects,
            "WebglBuffergeometryInstancingInterleavedObject",
            &objectData,
            sizeof(objectData),
            1u);
        appendInterleavedBufferPayload(
            allocation,
            WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                instances,
            "WebglBuffergeometryInstancingInterleavedInstances",
            instances.data(),
            instances.size() *
                sizeof(BuffergeometryInterleavedHostInstanceData),
            InstanceCount);
        appendInterleavedBufferPayload(
            allocation,
            WebglBuffergeometryInstancingInterleavedSceneRenderSetComponents::
                materials,
            "WebglBuffergeometryInstancingInterleavedMaterial",
            &materialData,
            sizeof(materialData),
            1u);
        appendInterleavedCrateTexture(
            allocation,
            crateTextureBytes,
            crateMipOffsets);
        encoder->allocEntity(allocation);
        renderer.executeRenderSetCommand(SceneRenderSetHandle, encoder);
    }

    void BuffergeometryInterleavedRuntimeAdapter::beforeFrame(
        GVM::Core::AbstractRendererImpl &renderer,
        const ThreeSampleHostOptions &options,
        uint32_t frameIndex)
    {
        (void)renderer;
        (void)options;
        (void)frameIndex;
    }

    void BuffergeometryInterleavedRuntimeAdapter::afterFrame(
        GVM::Core::AbstractRendererImpl &renderer,
        const ThreeSampleHostOptions &options,
        uint32_t frameIndex,
        GVM::RHI::Texture readbackTexture,
        uint32_t width,
        uint32_t height)
    {
        (void)renderer;
        if (captureWritten || frameIndex != options.targetFrame)
        {
            return;
        }
        const uint64_t byteCount =
            uint64_t(width) * uint64_t(height) * 4u;
        if (byteCount > std::numeric_limits<size_t>::max())
        {
            throw std::overflow_error(
                "Interleaved RGBA8 capture exceeds host storage.");
        }
        eastl::vector<uint8_t> rgba(static_cast<size_t>(byteCount));
        device->graphicsQueue(0)
            ->readTexture(
                readbackTexture,
                rgba.data(),
                rgba.size())
            ->submit();
        writeArtifacts(
            options,
            frameIndex,
            width,
            height,
            rgba);
        captureWritten = true;
    }

    void BuffergeometryInterleavedRuntimeAdapter::shutdown(
        GVM::Core::AbstractRendererImpl &renderer,
        const ThreeSampleHostOptions &options)
    {
        (void)renderer;
        (void)options;
        vertices.clear();
        indices.clear();
        instances.clear();
        crateTextureBytes.clear();
        crateMipOffsets.clear();
    }

    void BuffergeometryInterleavedRuntimeAdapter::writeArtifacts(
        const ThreeSampleHostOptions &options,
        uint32_t frameIndex,
        uint32_t width,
        uint32_t height,
        const eastl::vector<uint8_t> &rgba) const
    {
        if (!options.captureRgbaPath.empty())
        {
            const std::filesystem::path outputPath(
                options.captureRgbaPath.c_str());
            prepareInterleavedOutputPath(outputPath);
            std::ofstream output(
                outputPath,
                std::ios::binary |
                    std::ios::out |
                    std::ios::trunc);
            output.write(
                reinterpret_cast<const char *>(rgba.data()),
                static_cast<std::streamsize>(rgba.size()));
            if (!output)
            {
                throw std::runtime_error(
                    "Could not write interleaved RGBA capture.");
            }
        }
        if (!options.captureMetadataPath.empty())
        {
            const std::filesystem::path outputPath(
                options.captureMetadataPath.c_str());
            prepareInterleavedOutputPath(outputPath);
            std::ofstream output(outputPath, std::ios::out | std::ios::trunc);
            output
                << "{\n"
                << "  \"schemaVersion\":1,\n"
                << "  \"source\":\"gvm-three-r185\",\n"
                << "  \"caseId\":\"webgl_buffergeometry_instancing_interleaved\",\n"
                << "  \"scenarioId\":\"" << options.scenarioId.c_str() << "\",\n"
                << "  \"pipeline\":\"" << options.pipeline.c_str() << "\",\n"
                << "  \"backend\":\"" << threeSampleBackendName(options.backend) << "\",\n"
                << "  \"frame\":" << frameIndex << ",\n"
                << "  \"randomSeed\":" << options.randomSeed << ",\n"
                << "  \"width\":" << width << ",\n"
                << "  \"height\":" << height << ",\n"
                << "  \"rowStrideBytes\":" << uint64_t(width) * 4u << ",\n"
                << "  \"byteCount\":" << rgba.size() << ",\n"
                << "  \"format\":\"rgba8unorm\"\n"
                << "}\n";
        }
        if (!options.sceneSnapshotPath.empty())
        {
            const std::filesystem::path outputPath(
                options.sceneSnapshotPath.c_str());
            prepareInterleavedOutputPath(outputPath);
            std::ofstream output(outputPath, std::ios::out | std::ios::trunc);
            output
                << "{\n"
                << "  \"schemaVersion\":1,\n"
                << "  \"caseId\":\"webgl_buffergeometry_instancing_interleaved\",\n"
                << "  \"scenarioId\":\"" << options.scenarioId.c_str() << "\",\n"
                << "  \"frame\":" << frameIndex << ",\n"
                << "  \"implementationLevel\":\"semantic-complete\",\n"
                << "  \"gpuWorkDslOnly\":true,\n"
                << "  \"renderSetPolicy\":\"required\",\n"
                << "  \"sceneRenderSetCount\":1,\n"
                << "  \"renderableObjectCount\":1,\n"
                << "  \"entityCount\":1,\n"
                << "  \"instanceCount\":5000,\n"
                << "  \"vertexCount\":24,\n"
                << "  \"indexCount\":36,\n"
                << "  \"scenePassCount\":1,\n"
                << "  \"screenPassCount\":0,\n"
                << "  \"drawCommandCount\":1,\n"
                << "  \"finalRandomState\":" << finalRandomState << ",\n"
                << "  \"renderSetType\":\"WebglBuffergeometryInstancingInterleavedSceneRenderSet\",\n"
                << "  \"componentSchema\":["
                << "{\"name\":\"vertices\",\"kind\":\"buffer\",\"role\":\"vertex\"},"
                << "{\"name\":\"indices\",\"kind\":\"buffer\",\"role\":\"index\"},"
                << "{\"name\":\"objects\",\"kind\":\"buffer\",\"role\":\"object\"},"
                << "{\"name\":\"instances\",\"kind\":\"buffer\",\"role\":\"instance\"},"
                << "{\"name\":\"materials\",\"kind\":\"buffer\",\"role\":\"material\"},"
                << "{\"name\":\"textures\",\"kind\":\"texture\",\"role\":\"texture\"}],\n"
                << "  \"sceneRoots\":[{\n"
                << "    \"id\":\"scene\",\n"
                << "    \"renderSetCount\":1,\n"
                << "    \"renderSetId\":\"scene-set\",\n"
                << "    \"renderSetType\":\"WebglBuffergeometryInstancingInterleavedSceneRenderSet\",\n"
                << "    \"renderableObjectCount\":1,\n"
                << "    \"entityCount\":1,\n"
                << "    \"entities\":[{\"entityId\":0,\"logicalRenderableId\":\"instanced-boxes\",\"instanceCount\":5000}],\n"
                << "    \"componentSchema\":["
                << "{\"name\":\"vertices\",\"kind\":\"buffer\",\"role\":\"vertex\"},"
                << "{\"name\":\"indices\",\"kind\":\"buffer\",\"role\":\"index\"},"
                << "{\"name\":\"objects\",\"kind\":\"buffer\",\"role\":\"object\"},"
                << "{\"name\":\"instances\",\"kind\":\"buffer\",\"role\":\"instance\"},"
                << "{\"name\":\"materials\",\"kind\":\"buffer\",\"role\":\"material\"},"
                << "{\"name\":\"textures\",\"kind\":\"texture\",\"role\":\"texture\"}],\n"
                << "    \"drawCommandCount\":1,\n"
                << "    \"directDrawFallback\":false,\n"
                << "    \"scenePasses\":[{\"name\":\"main-textured-instances\","
                << "\"renderClass\":\"WebglBuffergeometryInstancingInterleavedMainPass\","
                << "\"renderSetId\":\"scene-set\",\"renderSetBindingCount\":1,"
                << "\"drawMode\":\"render-set-indexed-indirect\",\"invocationCount\":1,"
                << "\"drawCommandCount\":1,\"usesStandaloneGeometry\":false,"
                << "\"usesExplicitDrawCount\":false}]\n"
                << "  }],\n"
                << "  \"scenePassSequence\":[{\"sceneRoot\":\"scene\","
                << "\"scenePass\":\"main-textured-instances\",\"entityOrdinal\":0}],\n"
                << "  \"usesRenderEntityID\":true,\n"
                << "  \"usesRenderEntityInstanceID\":true,\n"
                << "  \"directDrawFallback\":false\n"
                << "}\n";
        }
        if (!options.semanticSnapshotPath.empty())
        {
            const std::filesystem::path outputPath(
                options.semanticSnapshotPath.c_str());
            prepareInterleavedOutputPath(outputPath);
            std::ofstream output(outputPath, std::ios::out | std::ios::trunc);
            output
                << "{\n"
                << "  \"schemaVersion\":1,\n"
                << "  \"caseId\":\"webgl_buffergeometry_instancing_interleaved\",\n"
                << "  \"scenarioId\":\"" << options.scenarioId.c_str() << "\",\n"
                << "  \"frame\":" << frameIndex << ",\n"
                << "  \"asset\":\"textures/crate.gif\",\n"
                << "  \"assetSha256\":\"a890f0a89eadc083cb39bfbe597c1395d7acf47a19f673b5643d4a9c174ea52f\",\n"
                << "  \"randomDrawCount\":35108,\n"
                << "  \"finalRandomState\":" << finalRandomState << "\n"
                << "}\n";
        }
    }
} // namespace GVM::ThreeSamples
