#pragma once
// https://stackoverflow.com/questions/2124339/c-preprocessor-va-args-number-of-arguments
#define UGLCONCAT_(x, y) x##y
#define UGLCONCAT(x, y) UGLCONCAT_(x, y)
#define UGL_NUM_ARG(...) UGL_NUM_ARG_(__VA_ARGS__, UGL_RSEQ_N())
#define UGL_NUM_ARG_(...) UGL_ARG_N(__VA_ARGS__)
#define UGL_ARG_N(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, N, ...) N
#define UGL_RSEQ_N() 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0

#define DEPAREN(X) ESC(ISH X)
#define ISH(...) ISH __VA_ARGS__
#define ESC(...) ESC_(__VA_ARGS__)
#define ESC_(...) VAN##__VA_ARGS__
#define VANISH

#define MemberDef1(x) DEPAREN(x);
#define MemberDef2(x, ...) MemberDef1(x) MemberDef1(__VA_ARGS__)
#define MemberDef3(x, ...) MemberDef1(x) MemberDef2(__VA_ARGS__)
#define MemberDef4(x, ...) MemberDef1(x) MemberDef3(__VA_ARGS__)
#define MemberDef5(x, ...) MemberDef1(x) MemberDef4(__VA_ARGS__)
#define MemberDef6(x, ...) MemberDef1(x) MemberDef5(__VA_ARGS__)
#define MemberDef7(x, ...) MemberDef1(x) MemberDef6(__VA_ARGS__)
#define MemberDef8(x, ...) MemberDef1(x) MemberDef7(__VA_ARGS__)
#define MemberDef9(x, ...) MemberDef1(x) MemberDef8(__VA_ARGS__)
#define MemberDef10(x, ...) MemberDef1(x) MemberDef9(__VA_ARGS__)
#define MemberDef11(x, ...) MemberDef1(x) MemberDef10(__VA_ARGS__)
#define MemberDef12(x, ...) MemberDef1(x) MemberDef11(__VA_ARGS__)
#define MemberDef13(x, ...) MemberDef1(x) MemberDef12(__VA_ARGS__)
#define MemberDef14(x, ...) MemberDef1(x) MemberDef13(__VA_ARGS__)
#define MemberDef15(x, ...) MemberDef1(x) MemberDef14(__VA_ARGS__)
#define MemberDef16(x, ...) MemberDef1(x) MemberDef15(__VA_ARGS__)
#define MemberDef17(x, ...) MemberDef1(x) MemberDef16(__VA_ARGS__)
#define MemberDef18(x, ...) MemberDef1(x) MemberDef17(__VA_ARGS__)
#define MemberDef19(x, ...) MemberDef1(x) MemberDef18(__VA_ARGS__)
#define MemberDef20(x, ...) MemberDef1(x) MemberDef19(__VA_ARGS__)
#define MemberDef21(x, ...) MemberDef1(x) MemberDef20(__VA_ARGS__)
#define MemberDef22(x, ...) MemberDef1(x) MemberDef21(__VA_ARGS__)
#define MemberDef23(x, ...) MemberDef1(x) MemberDef22(__VA_ARGS__)
#define MemberDef24(x, ...) MemberDef1(x) MemberDef23(__VA_ARGS__)
#define MemberDef25(x, ...) MemberDef1(x) MemberDef24(__VA_ARGS__)
#define MemberDef26(x, ...) MemberDef1(x) MemberDef25(__VA_ARGS__)
#define MemberDef27(x, ...) MemberDef1(x) MemberDef26(__VA_ARGS__)
#define MemberDef28(x, ...) MemberDef1(x) MemberDef27(__VA_ARGS__)
#define MemberDef29(x, ...) MemberDef1(x) MemberDef28(__VA_ARGS__)
#define MemberDef30(x, ...) MemberDef1(x) MemberDef29(__VA_ARGS__)
#define MemberDef31(x, ...) MemberDef1(x) MemberDef30(__VA_ARGS__)
#define MemberDef32(x, ...) MemberDef1(x) MemberDef31(__VA_ARGS__)
#define MemberDef33(x, ...) MemberDef1(x) MemberDef32(__VA_ARGS__)
#define MemberDef34(x, ...) MemberDef1(x) MemberDef33(__VA_ARGS__)
#define MemberDef35(x, ...) MemberDef1(x) MemberDef34(__VA_ARGS__)
#define MemberDef36(x, ...) MemberDef1(x) MemberDef35(__VA_ARGS__)
#define MemberDef37(x, ...) MemberDef1(x) MemberDef36(__VA_ARGS__)
#define MemberDef38(x, ...) MemberDef1(x) MemberDef37(__VA_ARGS__)
#define MemberDef39(x, ...) MemberDef1(x) MemberDef38(__VA_ARGS__)
#define MemberDef40(x, ...) MemberDef1(x) MemberDef39(__VA_ARGS__)
#define MemberDef41(x, ...) MemberDef1(x) MemberDef40(__VA_ARGS__)
#define MemberDef42(x, ...) MemberDef1(x) MemberDef41(__VA_ARGS__)
#define MemberDef43(x, ...) MemberDef1(x) MemberDef42(__VA_ARGS__)
#define MemberDef44(x, ...) MemberDef1(x) MemberDef43(__VA_ARGS__)
#define MemberDef45(x, ...) MemberDef1(x) MemberDef44(__VA_ARGS__)
#define MemberDef46(x, ...) MemberDef1(x) MemberDef45(__VA_ARGS__)
#define MemberDef47(x, ...) MemberDef1(x) MemberDef46(__VA_ARGS__)
#define MemberDef48(x, ...) MemberDef1(x) MemberDef47(__VA_ARGS__)
#define MemberDef49(x, ...) MemberDef1(x) MemberDef48(__VA_ARGS__)
#define MemberDef50(x, ...) MemberDef1(x) MemberDef49(__VA_ARGS__)
#define MemberDef51(x, ...) MemberDef1(x) MemberDef50(__VA_ARGS__)
#define MemberDef52(x, ...) MemberDef1(x) MemberDef51(__VA_ARGS__)
#define MemberDef53(x, ...) MemberDef1(x) MemberDef52(__VA_ARGS__)
#define MemberDef54(x, ...) MemberDef1(x) MemberDef53(__VA_ARGS__)
#define MemberDef55(x, ...) MemberDef1(x) MemberDef54(__VA_ARGS__)
#define MemberDef56(x, ...) MemberDef1(x) MemberDef55(__VA_ARGS__)
#define MemberDef57(x, ...) MemberDef1(x) MemberDef56(__VA_ARGS__)
#define MemberDef58(x, ...) MemberDef1(x) MemberDef57(__VA_ARGS__)
#define MemberDef59(x, ...) MemberDef1(x) MemberDef58(__VA_ARGS__)
#define MemberDef60(x, ...) MemberDef1(x) MemberDef59(__VA_ARGS__)
#define MemberDef61(x, ...) MemberDef1(x) MemberDef60(__VA_ARGS__)
#define MemberDef62(x, ...) MemberDef1(x) MemberDef61(__VA_ARGS__)
#define MemberDef63(x, ...) MemberDef1(x) MemberDef62(__VA_ARGS__)
#define MemberDef64(x, ...) MemberDef1(x) MemberDef63(__VA_ARGS__)

#define ParamDef1(x) DEPAREN(x)
#define ParamDef2(x, ...) ParamDef1(x), ParamDef1(__VA_ARGS__)
#define ParamDef3(x, ...) ParamDef1(x), ParamDef2(__VA_ARGS__)
#define ParamDef4(x, ...) ParamDef1(x), ParamDef3(__VA_ARGS__)
#define ParamDef5(x, ...) ParamDef1(x), ParamDef4(__VA_ARGS__)
#define ParamDef6(x, ...) ParamDef1(x), ParamDef5(__VA_ARGS__)
#define ParamDef7(x, ...) ParamDef1(x), ParamDef6(__VA_ARGS__)
#define ParamDef8(x, ...) ParamDef1(x), ParamDef7(__VA_ARGS__)
#define ParamDef9(x, ...) ParamDef1(x), ParamDef8(__VA_ARGS__)
#define ParamDef10(x, ...) ParamDef1(x), ParamDef9(__VA_ARGS__)
#define ParamDef11(x, ...) ParamDef1(x), ParamDef10(__VA_ARGS__)
#define ParamDef12(x, ...) ParamDef1(x), ParamDef11(__VA_ARGS__)
#define ParamDef13(x, ...) ParamDef1(x), ParamDef12(__VA_ARGS__)
#define ParamDef14(x, ...) ParamDef1(x), ParamDef13(__VA_ARGS__)
#define ParamDef15(x, ...) ParamDef1(x), ParamDef14(__VA_ARGS__)
#define ParamDef16(x, ...) ParamDef1(x), ParamDef15(__VA_ARGS__)
#define ParamDef17(x, ...) ParamDef1(x), ParamDef16(__VA_ARGS__)
#define ParamDef18(x, ...) ParamDef1(x), ParamDef17(__VA_ARGS__)
#define ParamDef19(x, ...) ParamDef1(x), ParamDef18(__VA_ARGS__)
#define ParamDef20(x, ...) ParamDef1(x), ParamDef19(__VA_ARGS__)
#define ParamDef21(x, ...) ParamDef1(x), ParamDef20(__VA_ARGS__)
#define ParamDef22(x, ...) ParamDef1(x), ParamDef21(__VA_ARGS__)
#define ParamDef23(x, ...) ParamDef1(x), ParamDef22(__VA_ARGS__)
#define ParamDef24(x, ...) ParamDef1(x), ParamDef23(__VA_ARGS__)
#define ParamDef25(x, ...) ParamDef1(x), ParamDef24(__VA_ARGS__)
#define ParamDef26(x, ...) ParamDef1(x), ParamDef25(__VA_ARGS__)
#define ParamDef27(x, ...) ParamDef1(x), ParamDef26(__VA_ARGS__)
#define ParamDef28(x, ...) ParamDef1(x), ParamDef27(__VA_ARGS__)
#define ParamDef29(x, ...) ParamDef1(x), ParamDef28(__VA_ARGS__)
#define ParamDef30(x, ...) ParamDef1(x), ParamDef29(__VA_ARGS__)
#define ParamDef31(x, ...) ParamDef1(x), ParamDef30(__VA_ARGS__)
#define ParamDef32(x, ...) ParamDef1(x), ParamDef31(__VA_ARGS__)
#define ParamDef33(x, ...) ParamDef1(x), ParamDef32(__VA_ARGS__)
#define ParamDef34(x, ...) ParamDef1(x), ParamDef33(__VA_ARGS__)
#define ParamDef35(x, ...) ParamDef1(x), ParamDef34(__VA_ARGS__)
#define ParamDef36(x, ...) ParamDef1(x), ParamDef35(__VA_ARGS__)
#define ParamDef37(x, ...) ParamDef1(x), ParamDef36(__VA_ARGS__)
#define ParamDef38(x, ...) ParamDef1(x), ParamDef37(__VA_ARGS__)
#define ParamDef39(x, ...) ParamDef1(x), ParamDef38(__VA_ARGS__)
#define ParamDef40(x, ...) ParamDef1(x), ParamDef39(__VA_ARGS__)
#define ParamDef41(x, ...) ParamDef1(x), ParamDef40(__VA_ARGS__)
#define ParamDef42(x, ...) ParamDef1(x), ParamDef41(__VA_ARGS__)
#define ParamDef43(x, ...) ParamDef1(x), ParamDef42(__VA_ARGS__)
#define ParamDef44(x, ...) ParamDef1(x), ParamDef43(__VA_ARGS__)
#define ParamDef45(x, ...) ParamDef1(x), ParamDef44(__VA_ARGS__)
#define ParamDef46(x, ...) ParamDef1(x), ParamDef45(__VA_ARGS__)
#define ParamDef47(x, ...) ParamDef1(x), ParamDef46(__VA_ARGS__)
#define ParamDef48(x, ...) ParamDef1(x), ParamDef47(__VA_ARGS__)
#define ParamDef49(x, ...) ParamDef1(x), ParamDef48(__VA_ARGS__)
#define ParamDef50(x, ...) ParamDef1(x), ParamDef49(__VA_ARGS__)
#define ParamDef51(x, ...) ParamDef1(x), ParamDef50(__VA_ARGS__)
#define ParamDef52(x, ...) ParamDef1(x), ParamDef51(__VA_ARGS__)
#define ParamDef53(x, ...) ParamDef1(x), ParamDef52(__VA_ARGS__)
#define ParamDef54(x, ...) ParamDef1(x), ParamDef53(__VA_ARGS__)
#define ParamDef55(x, ...) ParamDef1(x), ParamDef54(__VA_ARGS__)
#define ParamDef56(x, ...) ParamDef1(x), ParamDef55(__VA_ARGS__)
#define ParamDef57(x, ...) ParamDef1(x), ParamDef56(__VA_ARGS__)
#define ParamDef58(x, ...) ParamDef1(x), ParamDef57(__VA_ARGS__)
#define ParamDef59(x, ...) ParamDef1(x), ParamDef58(__VA_ARGS__)
#define ParamDef60(x, ...) ParamDef1(x), ParamDef59(__VA_ARGS__)
#define ParamDef61(x, ...) ParamDef1(x), ParamDef60(__VA_ARGS__)
#define ParamDef62(x, ...) ParamDef1(x), ParamDef61(__VA_ARGS__)
#define ParamDef63(x, ...) ParamDef1(x), ParamDef62(__VA_ARGS__)
#define ParamDef64(x, ...) ParamDef1(x), ParamDef63(__VA_ARGS__)

#define UGL_CTOR_FUNC [[clang::annotate("UGLCTORFUNC")]]

#define constructor(...) \
public:                  \
    UGLCONCAT(MemberDef, UGL_NUM_ARG(__VA_ARGS__))(__VA_ARGS__) UGL_CTOR_FUNC void create(UGLCONCAT(ParamDef, UGL_NUM_ARG(__VA_ARGS__))(__VA_ARGS__))