function(UGLCOMPILE_LINTER TARGET_NAME SRC_FILE OUTPUT_PATH)
    set(UGLTempMainPath "${OUTPUT_PATH}/UGLTemp/${TARGET_NAME}.cpp")
    file(MAKE_DIRECTORY "${OUTPUT_PATH}/UGLTemp")
    file(WRITE "${UGLTempMainPath}" "#include \"${SRC_FILE}\"\n int main(){return 0;}")
    add_executable(${TARGET_NAME} ${UGLTempMainPath})
endfunction()

function(UGLCOMPILE_GENERATED_HEADERS GENERATED_TARGET SRC_FILE OUTPUT_PATH UGL_COMPILER)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs INCLUDE_DIRS DSL_DIRS UGLC_ARGS)
    cmake_parse_arguments(UGLC "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    # `INCLUDE_DIRS` drives Clang parsing and dependency tracking.
    # `DSL_DIRS` precisely controls which headers UGLC may flatten into the
    # generated single-header output.
    get_filename_component(_UGLC_SOURCE_DIR "${SRC_FILE}" DIRECTORY)
    set(_UGLC_INCLUDE_DIRS ${UGLC_COMMON_INCLUDE_DIRS} ${UGLC_INCLUDE_DIRS} ${UGLC_UNPARSED_ARGUMENTS})
    set(_UGLC_DSL_DIRS ${UGLC_DSL_DIRS} "${_UGLC_SOURCE_DIR}")
    list(REMOVE_DUPLICATES _UGLC_INCLUDE_DIRS)
    list(REMOVE_DUPLICATES _UGLC_DSL_DIRS)
    set(_INCLUDE_DIRS_CMD "")
    set(_DSL_DIRS_CMD "")
    foreach(_dir IN LISTS _UGLC_INCLUDE_DIRS)
        list(APPEND _INCLUDE_DIRS_CMD  "-I${_dir}")
    endforeach()
    foreach(_dir IN LISTS _UGLC_DSL_DIRS)
        list(APPEND _DSL_DIRS_CMD "--dsl-dir" "${_dir}")
    endforeach()

    # 从 include 目录中递归收集头文件
    set(INCLUDE_DIRS ${_UGLC_INCLUDE_DIRS} ${_UGLC_DSL_DIRS})
    list(REMOVE_DUPLICATES INCLUDE_DIRS)
    set(UGL_DEP_HEADERS "")
    foreach(dir IN LISTS INCLUDE_DIRS)
        if(IS_DIRECTORY "${dir}")
            file(GLOB_RECURSE _one_dir_headers
                CONFIGURE_DEPENDS        # 关键：目录内容变化会触发重新 configure
                "${dir}/*.h"
                "${dir}/*.hpp"
            )
            list(APPEND UGL_DEP_HEADERS ${_one_dir_headers})
        endif()
    endforeach()

    list(REMOVE_DUPLICATES UGL_DEP_HEADERS)

    # 生成一个临时文件（如果需要）
    #file(WRITE "${OUTPUT_PATH}/bin.hpp" "// Placeholder for bin.cpp generated by UGLC\n")

    file(MAKE_DIRECTORY "${OUTPUT_PATH}")
    set(GENERATED_HEADER "${OUTPUT_PATH}/temp_output.abc")

    set(UGL_COMPILER_COMMAND "${UGL_COMPILER}")
    set(UGL_COMPILER_DEPENDS "")
    if(TARGET "${UGL_COMPILER}")
        set(UGL_COMPILER_COMMAND "$<TARGET_FILE:${UGL_COMPILER}>")
        set(UGL_COMPILER_DEPENDS "${UGL_COMPILER}")
    elseif(UGL_COMPILER AND EXISTS "${UGL_COMPILER}")
        set(UGL_COMPILER_DEPENDS "${UGL_COMPILER}")
    else()
        message(FATAL_ERROR "UGLCOMPILE_GENERATED_HEADERS(${GENERATED_TARGET}) requires a valid UGLC target or executable path, got: ${UGL_COMPILER}")
    endif()

    set(_UGLC_RESOURCE_DIR_CMD "")
    if(DEFINED GVM_UGLC_RESOURCE_DIR AND NOT GVM_UGLC_RESOURCE_DIR STREQUAL "")
        list(APPEND _UGLC_RESOURCE_DIR_CMD "--resource-dir" "${GVM_UGLC_RESOURCE_DIR}")
    endif()

    add_custom_command(
        OUTPUT "${GENERATED_HEADER}"
        BYPRODUCTS
            "${OUTPUT_PATH}/generate_result.hpp"
            "${OUTPUT_PATH}/exports.hpp"
            "${OUTPUT_PATH}/dsl_single_header.hpp"
        COMMAND "${UGL_COMPILER_COMMAND}"
            -s "${SRC_FILE}"
            -o "${OUTPUT_PATH}"
            ${_UGLC_RESOURCE_DIR_CMD}
            ${_DSL_DIRS_CMD}
            ${UGLC_UGLC_ARGS}
            ${_INCLUDE_DIRS_CMD}    # 把处理好的 -I 路径列表直接展开
        COMMAND "${CMAKE_COMMAND}" -E touch "${GENERATED_HEADER}"
        DEPENDS
            ${UGL_COMPILER_DEPENDS}
            "${SRC_FILE}"
            ${UGL_DEP_HEADERS}     # 这里真正“监控”所有头文件
        #WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        #COMMENT "Running UGLC compiler on ${SRC_FILE} with includes: ${_INCLUDE_DIRS_RESULT}"
        COMMENT "Running UGLC compiler with cmd: ${UGL_COMPILER_COMMAND} -s ${SRC_FILE} -o ${OUTPUT_PATH} ${_UGLC_RESOURCE_DIR_CMD} ${UGLC_UGLC_ARGS} ${_INCLUDE_DIRS_CMD}"
        VERBATIM
    )


    # 用一个自定义 target 挂这个输出（或直接加到 target_sources 里）
    add_custom_target("${GENERATED_TARGET}" DEPENDS "${GENERATED_HEADER}")
endfunction()

function(UGLCOMPILE TARGET_NAME SRC_FILE OUTPUT_PATH UGL_COMPILER)
    target_compile_definitions(${TARGET_NAME} PRIVATE DISABLE_UGL GLM_ENABLE_EXPERIMENTAL)
    target_include_directories(${TARGET_NAME} PRIVATE "${OUTPUT_PATH}")
    get_filename_component(_UGLC_OUTPUT_PARENT_DIR "${OUTPUT_PATH}" DIRECTORY)
    target_include_directories(${TARGET_NAME} PRIVATE "${_UGLC_OUTPUT_PARENT_DIR}")

    set(GENERATED_TARGET "${TARGET_NAME}_UGLCodeGen")
    UGLCOMPILE_GENERATED_HEADERS("${GENERATED_TARGET}" "${SRC_FILE}" "${OUTPUT_PATH}" "${UGL_COMPILER}" ${ARGN})
    # 让 ${TARGET_NAME} 依赖这个自定义目标
    add_dependencies("${TARGET_NAME}" "${GENERATED_TARGET}")
endfunction()
