#pragma once

#include "Host/ThreeSampleHostOptions.hpp"

#include <GVMCore/GVMCore.Public.hpp>
#include <GVMCore/Private/GDeviceProxy.hpp>

#include <EASTL/array.h>
#include <EASTL/string.h>
#include <EASTL/vector.h>

#include <glm/mat4x4.hpp>
#include <glm/vec4.hpp>

namespace GVM::ThreeSamples
{
    /** Mirrors the packed Scene attribute union generated by UGLC. */
    struct alignas(16) TerrainRaycastHostVertex
    {
        glm::vec4 position;
        glm::vec4 normal;
        glm::vec4 uv;
    };

    /** Mirrors one RenderSet entity transform and projection component. */
    struct alignas(16) TerrainRaycastHostObjectData
    {
        glm::mat4 modelView;
        glm::mat4 projection;
    };

    /** Mirrors the required non-instanced component record. */
    struct alignas(16) TerrainRaycastHostInstanceData
    {
        glm::vec4 reserved;
    };

    /** Mirrors the terrain or normal-cone material selector. */
    struct alignas(16) TerrainRaycastHostMaterialData
    {
        glm::vec4 phaseAndReserved;
    };

    /** Stores one packed RenderSet entity before allocation. */
    struct TerrainRaycastEntityState
    {
        eastl::string logicalId;
        eastl::vector<TerrainRaycastHostVertex> vertices;
        eastl::vector<uint32_t> indices;
        TerrainRaycastHostObjectData objectData = {};
        TerrainRaycastHostInstanceData instanceData = {};
        TerrainRaycastHostMaterialData materialData = {};
        GVM::Core::RenderEntityIndex entityIndex = UINT32_MAX;
    };

    /** Connects deterministic CPU terrain and picking to the dedicated renderer. */
    class WebglGeometryTerrainRaycastRuntimeAdapter final
    {
    public:
        /** Generates texture data through DSL Compute and allocates two entities. */
        template <class RendererImpl>
        void initialize(
            RendererImpl &renderer,
            GVM::Core::DeviceProxy inDevice,
            const ThreeSampleHostOptions &options)
        {
            initializeCpuState(inDevice, options);
            renderer.generateTerrainTexture(
                heights,
                grain,
                terrainTexture);
            allocateScene(renderer, options);
        }

        /** Keeps the frozen camera and CPU raycast result stable per frame. */
        void beforeFrame(
            GVM::Core::AbstractRendererImpl &renderer,
            const ThreeSampleHostOptions &options,
            uint32_t frameIndex);

        /** Captures RGBA8 output and the one-Set structural contract. */
        void afterFrame(
            GVM::Core::AbstractRendererImpl &renderer,
            const ThreeSampleHostOptions &options,
            uint32_t frameIndex,
            GVM::RHI::Texture readbackTexture,
            uint32_t width,
            uint32_t height);

        /** Releases all private CPU storage after renderer teardown. */
        void shutdown(
            GVM::Core::AbstractRendererImpl &renderer,
            const ThreeSampleHostOptions &options);

    private:
        /** Validates the locked scenario and constructs deterministic CPU data. */
        void initializeCpuState(
            GVM::Core::DeviceProxy inDevice,
            const ThreeSampleHostOptions &options);

        /** Allocates the terrain and helper through the exported unique Set. */
        void allocateScene(
            GVM::Core::AbstractRendererImpl &renderer,
            const ThreeSampleHostOptions &options);

        GVM::Core::DeviceProxy device;
        eastl::array<TerrainRaycastEntityState, 2u> entities;
        eastl::vector<uint32_t> heights;
        eastl::vector<uint32_t> grain;
        eastl::vector<uint8_t> terrainTexture;
        bool captureWritten = false;
    };
} // namespace GVM::ThreeSamples
